import { ReactNode } from 'react'
import { Plus_Jakarta_Sans } from 'next/font/google'
import { StylesProvider } from '@/providers/StylesProvider'

const plusJakartaSans = Plus_Jakarta_Sans({ subsets: ['latin'] })

interface RootLayoutProps {
  children: ReactNode
}

export const metadata = {
  title: 'Leadster Page',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={plusJakartaSans.className}>
        <StylesProvider>{children}</StylesProvider>
      </body>
    </html>
  )
}
